server:
  port: 8080

spring:
  datasource:
#    name: recyc
    url: jdbc:mysql://localhost:3306/recyc?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    schema:
#    - classpath:schema.sql
#    data:
#    - classpath:data.sql
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    password: recyc123456
    port: 25
    protocol: smtp
    username: zkjc_recyc@163.com


  server:
    tomcat:
      uri-encoding: UTF-8

mybatis:
  type-aliases-package: com.zkjc.recyc.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"